import type { Metadata } from "next";
import { Outfit, Source_Sans_3 } from "next/font/google";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import { site } from "@/lib/site";
import "./globals.css";

// Display: Outfit — geometric, strong caps, sits naturally next to the
// wordmark in the lockup. Body: Source Sans 3 — quiet humanist sans that
// reads well small (hours tables, addresses).
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
});
const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-source-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: `${site.name} | Local Grocery Store in Grand Rapids, MI`,
    template: `%s | ${site.name}`,
  },
  description: site.description,
  metadataBase: new URL(site.url),
  // Icons + OpenGraph image come from the static files in app/
  // (icon.png, apple-icon.png, opengraph-image.png — generated by
  // scripts/brand-assets.mjs from public/brand/).
  openGraph: {
    title: site.name,
    description: site.description,
    url: site.url,
    siteName: site.name,
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable} ${sourceSans.variable}`}>
      <body className="bg-cream text-ink font-sans antialiased min-h-screen flex flex-col text-[17px] leading-relaxed">
        <Nav />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
